runtime: java21
env: standard
service: analytics-service
instance_class: F1
entrypoint: java -jar target/analytics-service-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 5

env_variables:
  JWT_SECRET: mySuperSecretKeyThatIsVeryLongAndSecureForJWTTokenGeneration2025
  JWT_EXPIRATION: "86400000"